spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: FTNATSULOL1

  mail:
    host: smtp.126.com
    username: ekko30@126.com
    password: SEKBTVETTMWULYPU
    port: 465
    properties:
      from: ekko30@126.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  redis:
    host: 192.168.206.128

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: none


